on: [pull_request]

name: Check TSLint

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Installation
        run: yarn install --ignore-scripts
      - name: Check TSLint
        run: yarn lint
      - name: Build
        run: yarn build
        env:
          CI: true
